//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public decimal amount { get; set; }
        public string payment_method { get; set; }
        public string status { get; set; }
        public string transaction_id { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
